/*
 * This source file was generated by the Gradle 'init' task
 */
package bibliemprunt;

import bibliemprunt.données.BanqueClient;
import bibliemprunt.données.BanqueEmprunts;
import bibliemprunt.données.BanqueLivres;
import bibliemprunt.models.Emprunt;

import java.util.Scanner;

public class Bibliothèque {

    private static Borne borne;

    public static void main(String[] args) {
        initialisation();
        exécution();
        destruction();
    }

    private static void initialisation() {
        System.out.println("Système de Borne d'Emprunt");
        System.out.println("Initialisation de la bibliothèque...");

        Paramètre.initialiser();
        BanqueClient.initialiser();
        BanqueLivres.initialiser();
        BanqueEmprunts.initialiser();

        borne = new Borne();

        Runtime.getRuntime().addShutdownHook(new Thread() {
            @Override
            public void run() {
                borne.sigkillQuitter();
                borne.miseÀJour();
                destruction();
            }
        });

        System.out.println("Système initialisé avec succès!\n");
    }

    private static void exécution() {
        while (borne.estActive) {
            borne.miseÀJour();
        }
    }

    private static void destruction() {
        System.out.println("Fermeture du système...");

        borne.destruction();
        System.out.println("\nAu revoir!");
    }
}
