/*
 * This source file was generated by the Gradle 'init' task
 */
package bibliemprunt;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.util.HashMap;
import java.util.Map;
import java.awt.Desktop;

public class HTTPServeurPrototype {

    private enum HTTPRequêteType {
        POST,
        GET,
        HEAD,
        PUT,
        DELETE,
        CONNECT,
        OPTIONS,
        TRACE,
        PATCH
    }

    private static class HTTPMessage {
        public HTTPRequêteType requêteType;
        public String chemin;
    }

    private final static int interfacePort = 8080;
    private final static String interfaceURL = "http://127.0.0.1:" + interfacePort;

    private static ServerSocket serverSocket;
    private static Socket socket;
    private static BufferedReader socketInStrings;
    private static BufferedWriter socketOutStrings;
    private static BufferedInputStream socketInBytes;
    private static BufferedOutputStream socketOutBytes;

    private static HashMap<String, String> mimeTypeExtensionsSupportées = new HashMap<>(Map.of(
            "html", "text/html",
            "css", "text/css",
            "js", "application/javascript",
            "json", "application/json",
            "ico", "image/x-icon",
            "png", "image/png",
            "jpeg", "image/jpeg",
            "jpg", "image/jpg",
            "gif", "image/gif",
            "pdf", "image/pdf"));

    public static void main(String[] args) throws IOException, URISyntaxException, InterruptedException {
        System.out.println("Hello World!");

        // lancerNavigateur();

        serverSocket = new ServerSocket(interfacePort);

        while (true) {
            socket = serverSocket.accept();

            socketInStrings = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            socketOutStrings = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));
            socketInBytes = new BufferedInputStream(socket.getInputStream());
            socketOutBytes = new BufferedOutputStream(socket.getOutputStream());

            HTTPMessage message = recevoirMessage();
            boolean messageGéré = gérerMessage(message);
            if (!messageGéré) {
                envoyerMessage("{\"erreur\":\"Une erreur s'est produite du côté serveur.\"}", "application/json", 500);
            }

            socket.close();
        }

        // serverSocket.close();

    }

    private static void lancerNavigateur() throws URISyntaxException, IOException {
        // Première option : l'API Desktop de java est capable de
        // lancer la fenêtre par défaut de l'utilisateur.
        // Devrait fonctionner pour : Windows, Mac, Linux sur Gnome
        if (Desktop.isDesktopSupported()) {
            Desktop.getDesktop().browse(new URI(interfaceURL));
            return;
        }

        String nomSE = System.getProperty("os.name");
        if (nomSE.compareTo("Linux") == 0) {
            // Certaines distributions Linux ne viennent pas avec Gnome par défaut.
            // Deuxième option : utiliser la commande xdg-open qui vient avec xdg-utils
            // Devrait fonctionner pour : Toute distribution basée sur Ubuntu

            // Détecter xdg-open
            Runtime runtime = Runtime.getRuntime();
            Process which = runtime.exec(new String[] { "which", "xdg-open" });
            if (which.exitValue() == 0) {
                Process xdgOpen = runtime.exec(new String[] { "xdg-open", interfaceURL });
                if (xdgOpen.exitValue() == 0) {
                    return;
                }
            }

            // Certaines distributions ne viennent pas avec xdg-utils
            // Troisième option : utiliser une des diverses commandes qui pourraient être
            // sur le système

            String[] gestionnairesNavigateurs = new String[] { "open", "www-open", "x-www-open", "gnome-open",
                    "sensible-browser" };
            for (int i = 0; i < gestionnairesNavigateurs.length; i++) {
                which = runtime.exec(new String[] { "which", "sensible-browser" });
                if (which.exitValue() == 0) {
                    if (i == 3) {
                        System.err.println("Pouvez-vous me dire comment vous avez gnome-open, mais pas GNOME?");
                    }
                    Process proc = runtime
                            .exec(new String[] { gestionnairesNavigateurs[i], interfaceURL });
                    if (proc.exitValue() == 0) {
                        return;
                    }
                }
            }

            // Imaginons que rien de tout cela ne fonctionne...
            // Quatrième option : utiliser la variable d'environnement $BROWSER

            String navigateurEnv = System.getenv("BROWSER");
            if (navigateurEnv != null) {
                which = runtime.exec(new String[] { "which", navigateurEnv });
                if (which.exitValue() == 0) {
                    Process browser = runtime.exec(new String[] { "$BROWSER", interfaceURL });
                    if (browser.exitValue() == 0) {
                        return;
                    }
                }
            }

            // Peut-être python peut-il nous aider?
            // Cinquième option : lancer python3 -m webbrowser
            String pythonCommande = null;
            if (runtime.exec(new String[] { "which", "python3" }).exitValue() == 0) {
                pythonCommande = "python3";
            } else if (runtime.exec(new String[] { "which", "python" }).exitValue() == 0) {
                pythonCommande = "python";
            } else if (runtime.exec(new String[] { "which", "py" }).exitValue() == 0) {
                pythonCommande = "py";
            }

            if (pythonCommande != null) {
                Process pythonWeb = runtime
                        .exec(new String[] { pythonCommande, "-m", "webbrowser", interfaceURL });
                if (pythonWeb.exitValue() == 0) {
                    return;
                }
            }

            // Dernier recours : on teste tous les navigateurs majeurs
            String[] navigateursConnus = new String[] { "firefox", "mozilla", "epiphany", "konqueror",
                    "netscape", "opera", "links", "lynx", "chromium", "google-chrome" };
            for (int i = 0; i < navigateursConnus.length; i++) {
                which = runtime.exec(new String[] { "which", "sensible-browser" });
                if (which.exitValue() == 0) {
                    Process proc = runtime
                            .exec(new String[] { navigateursConnus[i], interfaceURL });
                    if (proc.exitValue() == 0) {
                        return;
                    }
                }
            }

            // Impossible d'ouvrir le navigateur.
            System.err.println(
                    "Nous n'avons pas été en mesure d'ouvrir un navigateur web sur votre machine.\n" +
                            "Cette application a besoin d'un navigateur web pour afficher son interface graphique.\n" +
                            "Veuillez utiliser une des options suivante : \n" +
                            "\t- installer xdg-open\n" +
                            "\t- changer la variable $BROWSER pour pointer vers un navigateur web\n" +
                            "\t- installer open\n" +
                            "\t- installer www-open\n" +
                            "\t- installer x-www-open\n" +
                            "\t- installer gnome-open\n" +
                            "\t- installer sensible-browser\n");
            System.exit(1);
        }

    }

    private static boolean gérerMessage(HTTPMessage message) throws IOException {
        if (message.requêteType == HTTPRequêteType.GET) {
            File fichier = new File("app/src/main/gui" + message.chemin);
            if (fichier.exists() && !fichier.isDirectory()) {
                String[] cheminParts = message.chemin.split("\\.");
                String extension = cheminParts[1];
                String mimeType = mimeTypeExtensionsSupportées.get(extension);
                /*
                 * "html", "text/html",
                 * "css", "text/css",
                 * "js", "application/javascript",
                 * "json", "application/json",
                 * "ico", "image/x-icon",
                 * "png", "image/png",
                 * "jpeg", "image/jpeg",
                 * "jpg", "image/jpg",
                 * "gif", "image/gif",
                 * "pdf", "image/pdf"));
                 */
                if (mimeType.compareTo("text/html") == 0 || mimeType.compareTo("text/css") == 0
                        || mimeType.compareTo("text/javascript") == 0) {
                    String fichierContenu = Files.readString(fichier.toPath());
                    envoyerMessage(fichierContenu, mimeType, 200);
                    return true;
                } else {
                    byte[] données = Files.readAllBytes(fichier.toPath());
                    envoyerMessage(données, mimeType, 200);
                }
            } else {
                envoyerMessage("<!DOCTYPE html><html><body><h1>404 Le fichier demandé n'existe pas.</h1></body></html>",
                        "text/html", 404);
                return true;
            }
        }

        return false;
    }

    private static void envoyerMessage(String message, String mimeType, int codeRéponse) throws IOException {
        socketOutStrings.write("HTTP/1.0 " + codeRéponse + "\n");
        socketOutStrings.write("Content-Type: " + mimeType + "\n");
        socketOutStrings.write("Content-Length: " + message.length() + "\n");
        socketOutStrings.write("\n");
        socketOutStrings.write(message);
        socketOutStrings.flush();
    }

    private static void envoyerMessage(byte[] message, String mimeType, int codeRéponse) throws IOException {
        socketOutStrings.write("HTTP/1.0 " + codeRéponse + "\n");
        socketOutStrings.write("Content-Type: " + mimeType + "\n");
        socketOutStrings.write("Content-Length: " + message.length + "\n");
        socketOutStrings.write("\n");
        socketOutStrings.flush();
        socketOutBytes.write(message);
        socketOutBytes.flush();
    }

    private static HTTPMessage recevoirMessage() throws IOException, InterruptedException {
        String[] lignes = new String[20];
        int nLignes = 0;
        String ligne;
        while (nLignes == 0) {
            ligne = socketInStrings.readLine();
            if (ligne == null) {
                Thread.sleep(100);
                continue;
            }

            while (!ligne.isEmpty()) {
                System.out.println(ligne);
                lignes[nLignes] = ligne;
                nLignes++;
                ligne = socketInStrings.readLine();
            }
            break;
        }

        return interpréterMessage(lignes, nLignes);
    }

    private static HTTPMessage interpréterMessage(String[] lignes, int nLignes) {
        HTTPRequêteType requêteType = HTTPRequêteType.valueOf(lignes[0].split(" ")[0]);
        String chemin = lignes[0].split(" ")[1];
        HTTPMessage message = new HTTPMessage();
        message.requêteType = requêteType;
        message.chemin = chemin;
        if (chemin.compareTo("/") == 0) {
            message.chemin = "/index.html";
        }
        return message;
    }

}
